version: '3'

services:
    php:
        build:
            context: ./php
        container_name: symfony_php
        volumes:
            - ../:/var/www/symfony
        environment:
            - SYMFONY_ENV=dev
        networks:
            - symfony_network

    nginx:
        image: nginx:latest
        container_name: symfony_nginx
        ports:
            - '8080:80'
        volumes:
            - ../public:/var/www/symfony/public
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - db
        networks:
            - symfony_network

    db:
        image: mariadb:10.4.20
        container_name: symfony_db
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: db
            MYSQL_USER: dev
            MYSQL_PASSWORD: dev
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
            - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - symfony_network

networks:
    symfony_network:
        driver: bridge

volumes:
    db_data:
